# Generated by Django 3.1.2 on 2020-10-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=20)),
                ('mantencion', models.BooleanField(choices=[(1, 'Si'), (2, 'No')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(choices=[(0, 'Comuna'), (1, 'La Reina'), (2, 'Ñuñoa'), (3, 'Providencia')], default=0, max_length=15)),
                ('bicicletasDisponibles', models.IntegerField()),
                ('direccion', models.TextField()),
                ('bicicleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bicicleta.bicicleta')),
            ],
        ),
    ]
