# Generated by Django 3.1.2 on 2020-10-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bicicleta', '0002_delete_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='mantencion',
            field=models.BooleanField(choices=[(1, 'Si'), (2, 'No')]),
        ),
    ]
