# Generated by Django 3.1.2 on 2020-10-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bicicleta', '0003_auto_20201022_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='mantencion',
            field=models.CharField(choices=[(1, 'Si'), (2, 'No')], default=2, max_length=2),
        ),
    ]
