# Generated by Django 3.1.2 on 2020-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bicicleta', '0004_auto_20201023_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='mantencion',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2),
        ),
    ]
