# Generated by Django 3.1.2 on 2020-10-27 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0002_remove_estacionamiento_bicicleta'),
        ('Bicicleta', '0005_auto_20201024_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='estacionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Estacionamiento.estacionamiento'),
        ),
    ]
