# Generated by Django 3.1.2 on 2020-10-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='bicicleta',
        ),
    ]
